In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("data.csv")
data.shape

(41664, 26)

In [4]:
data.head()

,time,Comms and Services,Space Heating,Hot Water,Sockets,Lighting,Bld_EngCons,Car Chargers,weekend,bank holiday,...,forecastperiod,forecast_temperature,forecast_feelslike,forecast_weathertype,forecast_windspeed,forecast_uvindex,forecast_precipitationprobability,forecast_winddirection,forecast_visibility,forecast_interval
0,2019-04-01 00:00:00+00,0.515253,0.856489,0.000000,0.051467,0.124797,1.548006,0.032239,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-04-01 01:00:00+00,0.687381,0.786147,0.085386,0.050931,0.151708,1.761553,0.042894,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-04-01 02:00:00+00,0.687678,3.530669,0.099239,0.055706,0.151233,4.524525,0.043100,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-04-01 03:00:00+00,0.690139,4.044003,0.098467,0.050019,0.151436,5.034064,0.043131,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-04-01 04:00:00+00,0.687081,4.223769,0.091533,0.050142,0.151331,5.203856,0.043031,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# make column names more code friendly
new_col_names_map =  {i: i.lower().replace(" ", "_") for i in data.columns}

data = data.rename(columns=new_col_names_map)
data.head()

,time,comms_and_services,space_heating,hot_water,sockets,lighting,bld_engcons,car_chargers,weekend,bank_holiday,...,forecastperiod,forecast_temperature,forecast_feelslike,forecast_weathertype,forecast_windspeed,forecast_uvindex,forecast_precipitationprobability,forecast_winddirection,forecast_visibility,forecast_interval
0,2019-04-01 00:00:00+00,0.515253,0.856489,0.000000,0.051467,0.124797,1.548006,0.032239,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-04-01 01:00:00+00,0.687381,0.786147,0.085386,0.050931,0.151708,1.761553,0.042894,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-04-01 02:00:00+00,0.687678,3.530669,0.099239,0.055706,0.151233,4.524525,0.043100,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-04-01 03:00:00+00,0.690139,4.044003,0.098467,0.050019,0.151436,5.034064,0.043131,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-04-01 04:00:00+00,0.687081,4.223769,0.091533,0.050142,0.151331,5.203856,0.043031,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data = data.set_index("time")

In [7]:
data.head()

,comms_and_services,space_heating,hot_water,sockets,lighting,bld_engcons,car_chargers,weekend,bank_holiday,hour,...,forecastperiod,forecast_temperature,forecast_feelslike,forecast_weathertype,forecast_windspeed,forecast_uvindex,forecast_precipitationprobability,forecast_winddirection,forecast_visibility,forecast_interval
time,,,,,,,,,,,,,,,,,,,,,
2019-04-01 00:00:00+00,0.515253,0.856489,0.000000,0.051467,0.124797,1.548006,0.032239,False,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-04-01 01:00:00+00,0.687381,0.786147,0.085386,0.050931,0.151708,1.761553,0.042894,False,False,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-04-01 02:00:00+00,0.687678,3.530669,0.099239,0.055706,0.151233,4.524525,0.043100,False,False,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-04-01 03:00:00+00,0.690139,4.044003,0.098467,0.050019,0.151436,5.034064,0.043131,False,False,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-04-01 04:00:00+00,0.687081,4.223769,0.091533,0.050142,0.151331,5.203856,0.043031,False,False,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
load_cols = ["comms_and_services", "space_heating", "hot_water", "sockets",
             "lighting", "bld_engcons", "car_chargers", "forecast_uvindex", "forecast_precipitationprobability"]
for col in load_cols:
  print(data[col].value_counts(normalize=True).head(5))

comms_and_services
0.714106    0.000123
0.711150    0.000098
0.710831    0.000098
0.713731    0.000098
0.712378    0.000098
Name: proportion, dtype: float64
space_heating
0.000000    0.000098
0.133572    0.000074
0.139786    0.000074
0.167714    0.000074
0.145506    0.000074
Name: proportion, dtype: float64
hot_water
0.000000    0.645251
0.000141    0.001029
0.000250    0.000907
0.000219    0.000735
0.000500    0.000711
Name: proportion, dtype: float64
sockets
0.000000    0.013942
0.023846    0.000147
0.033731    0.000123
0.033406    0.000123
0.106783    0.000123
Name: proportion, dtype: float64
lighting
0.000000    0.013917
0.147644    0.000221
0.147275    0.000172
0.147717    0.000172
0.147892    0.000147
Name: proportion, dtype: float64
bld_engcons
0.000000    0.020497
1.964978    0.000048
1.177000    0.000048
1.217450    0.000048
1.205183    0.000048
Name: proportion, dtype: float64
car_chargers
0.000000    0.725914
0.042978    0.000294
0.040992    0.000221
0.000141    0.000221
0.000025    0.000221
Name: proportion, dtype: float64
forecast_uvindex
0.0    0.494064
1.0    0.295001
2.0    0.054016
3.0    0.052642
4.0    0.046902
Name: proportion, dtype: float64
forecast_precipitationprobability
0.0    0.189717
1.0    0.078668
4.0    0.077344
5.0    0.062184
3.0    0.037090
Name: proportion, dtype: float64

In [9]:
data.columns

Index(['comms_and_services', 'space_heating', 'hot_water', 'sockets',
       'lighting', 'bld_engcons', 'car_chargers', 'weekend', 'bank_holiday',
       'hour', 'day_of_week', 'day_of_month', 'month', 'year',
       'forecast_datadate', 'forecastperiod', 'forecast_temperature',
       'forecast_feelslike', 'forecast_weathertype', 'forecast_windspeed',
       'forecast_uvindex', 'forecast_precipitationprobability',
       'forecast_winddirection', 'forecast_visibility', 'forecast_interval'],
      dtype='object')

In [25]:
test_data = data.copy()

cols = ["forecast_temperature", "forecast_feelslike"]
test_data = test_data[cols]
test_data = test_data.dropna(subset=cols, how="any")

In [30]:
from statsmodels.stats.weightstats import ztest as ztest

In [31]:
ztest(test_data[cols[0]], test_data[cols[1]], 
      value=data[cols[0]].mean() - data[cols[1]].mean(),
     alternative="two-sided",
     usevar="unequal")

(0.0, 1.0)